Internal Server Error: /
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'else'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/turismo/views.py", line 14, in home
    return render(request, 'turismo/home.html', {'lugares': lugares})
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
        (
    ...<2 lines>...
        )
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 567, in invalid_block_tag
    raise self.error(
    ...<8 lines>...
    )
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 195: 'else', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
"GET / HTTP/1.1" 500 249304
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Internal Server Error: /
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/turismo/views.py", line 14, in home
    return render(request, 'turismo/home.html', {'lugares': lugares})
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
"GET / HTTP/1.1" 500 246838
Internal Server Error: /
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/turismo/views.py", line 14, in home
    return render(request, 'turismo/home.html', {'lugares': lugares})
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
"GET / HTTP/1.1" 500 246975
Internal Server Error: /
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/turismo/views.py", line 14, in home
    return render(request, 'turismo/home.html', {'lugares': lugares})
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
"GET / HTTP/1.1" 500 246975
Internal Server Error: /
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/turismo/views.py", line 14, in home
    return render(request, 'turismo/home.html', {'lugares': lugares})
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/backends/django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
        contents,
    ...<2 lines>...
        self.engine,
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 299, in do_extends
    nodelist = parser.parse()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 518, in parse
    raise self.error(token, e)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/base.py", line 516, in parse
    compiled_result = compile_func(self, token)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/template/loader_tags.py", line 228, in do_block
    raise TemplateSyntaxError(
        "'%s' tag with name '%s' appears more than once" % (bits[0], block_name)
    )
django.template.exceptions.TemplateSyntaxError: 'block' tag with name 'content' appears more than once
"GET / HTTP/1.1" 500 246618
Internal Server Error: /usuarios/login/
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: axes_accessattempt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/usuarios/views.py", line 27, in login_usuario
    login(request, user)
    ~~~~~^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/contrib/auth/__init__.py", line 197, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/axes/signals.py", line 33, in handle_user_logged_in
    AxesProxyHandler.user_logged_in(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/axes/helpers.py", line 617, in inner
    return func(*args, **kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/axes/handlers/proxy.py", line 127, in user_logged_in
    return cls.get_implementation().user_logged_in(sender, request, user, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/axes/handlers/database.py", line 275, in user_logged_in
    self.clean_expired_user_attempts(request, credentials)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/axes/handlers/database.py", line 386, in clean_expired_user_attempts
    count, _ = AccessAttempt.objects.filter(attempt_time__lt=threshold).delete()
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/models/query.py", line 1196, in delete
    collector.collect(del_query)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/models/deletion.py", line 281, in collect
    new_objs = self.add(
        objs, source, nullable, reverse_dependency=reverse_dependency
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/models/deletion.py", line 124, in add
    if not objs:
           ^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/models/query.py", line 398, in __bool__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/models/query.py", line 1945, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: axes_accessattempt
"POST /usuarios/login/ HTTP/1.1" 500 194569
Internal Server Error: /usuarios/registro/
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/usuarios/views.py", line 16, in registrar_usuario
    return redirect('login')
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /usuarios/registro/ HTTP/1.1" 500 100309
Internal Server Error: /usuarios/registro/
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/usuarios/views.py", line 16, in registrar_usuario
    return redirect('login')
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 51, in redirect
    resolve_url(to, *args, **kwargs),
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/shortcuts.py", line 184, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
"POST /usuarios/registro/ HTTP/1.1" 500 99638
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/run/media/aquilivio/aquilivio/Projectos/Txopela_Tour/venv/lib64/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
